# Generated by Django 4.2.2 on 2023-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number_of_cylinders', models.PositiveIntegerField()),
                ('number_of_passengers', models.PositiveIntegerField()),
                ('Cylinder_volume', models.FloatField()),
                ('color', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified', '-created'],
            },
        ),
    ]
